title: "Almas Fathimah"
description: "Data Scientist | AI | Big Data | ML | Embedded Systems"
url: "https://almasfathimah124.github.io"
github_username: AlmasFathimah124
linkedin_username: almas-fathimah-90

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Resume Link
resume: /assets/AlmasFathimah_Resume.pdf


